### ISSUE TITLE
Expose opaque types to the user

### ISSUE THREAD

**Issue by halimamer** [pmodels/izem#2]
Currently, the user sees Izem types through the API. Since we assume C11 with atomics support, workarounds were necessary when the user's compiler does not support C11 atomics or conflicts with OpenMP occur (happens with production GNU as of gcc 6).

For example, a new type, `zm_atomic_ptr_t`, was created, which might be a C11 `atomic_intptr_t` when possible or a `volatile void*` when not possible. This works on the tested platforms, but it is gross, since we do explicit casting between the two different types.

All this wouldn't be necessary if the user only sees opaque objects. Internally, we do the necessary translation and only rely on C11 atomics. The `zm_***_t` type abstraction layer will no longer be needed.

**Comment by jeffhammond** [comment]
Channelling @goodell: `volatile` is **not** a valid substitute for an atomic type attribute.

I think https://github.com/pmodels/izem/issues/7 is a better way to address the absence of C11 support.

**Comment by halimamer** [comment]
After discussion with @jeffhammond, the conclusion was to keep the types exposed as they are and fix the dependence on C11 by a fallback to GCC builtin atomics support as suggested in #7.
