### ISSUE TITLE
support GCC intrinsics (__atomic and __sync) as fallback when C11 missing

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/izem#7]
I will submit PR for these later.

https://github.com/kjdev/apache-mod-fluentd/blob/master/configure.ac#L114 and https://github.com/kjdev/apache-mod-fluentd/blob/master/configure.ac#L126 will be useful.

**Comment by halimamer** [comment]
Note that this needs more than a configure check. We also need wrappers around the atomic types and operations. The current suggestion is to use C11 syntax with the `zm_` prefix and refactor the corresponding instances

**Comment by halimamer** [comment]
Fixed by 5a2538438590c4ab7a0f0feaf79ca5293271d33b
